### PR TITLE
Add subattributes to attributes

### PR DESCRIPTION
**Pull request by edeutsch**

### CODE REVIEW

**Review by vdancik — APPROVED** [review]

**Comment by edeutsch** [comment]
What about constraints for subattributes? How do we deal with that? and in /meta_knowledge_graph?

**Comment by vgardner-renci** [comment]
Waiting for DM committee to make a decision.

**Comment by edeutsch** [comment]
It became clear at today's data modeling call that while Attributes may have SubAttributes, it should not go any further than that. I have amended the PR to attempt to model that. Please review carefully!

**Comment by vgardner-renci** [comment]
@edeutsch -- Is this PR ready for review by the whole team?

**Comment by edeutsch** [comment]
yes, @vgardner-renci would you tag the whole team to review this?

**Review by RichardBruskiewich — APPROVED** [review]

**Review by bill-baumgartner — APPROVED** [review]

**Review by kshefchek — APPROVED** [review]

**Review by patrickkwang — APPROVED** [review]

**Review by rtroper — APPROVED** [review]

**Pull request merged**
