### PR TITLE
Update knowledge_level_agent_type_specification.md

### PR DESCRIPTION
**Pull request by mbrush**
Added note about short term plans for knowledge level annotations.

### CODE REVIEW

**Comment by andrewsu** [comment]
Personally, I don't love the link out to a google doc.  I would rather capture the relevant information in the MD file itself...

**Comment by mbrush** [comment]
Yes, I get that, and am  happy to translate the information into the markdown file. But it’s just stopgap measure for a couple months, and I just wanted people to know that they come to the specifications for guidance, and be able to see read what is going on in the short term while the permanent solution is implemented.  
This specification document is a work in progress anyway, and definitely won’t have the information referenced externally when it is finalized in the coming months

**Comment by edeutsch** [comment]
Modeling is still ongoing in the EPC calls. We discussed at TRAPI call 2023-10-12 and decided to leave this PR open until a fully fleshed-out markdown can be added to the PR.

**Comment by mbrush** [comment]
@edeutsch I made significant changes to the spec here to reflect its current state of implementation, which will complement the updated developer documentation I am creating.  This includes addition of more information to the spec md itself, rather than relying on linkouts to gdocs (there are still linkouts, but only for more supplementation info).  Can you approve/merge the PR?

**Review by edeutsch — APPROVED** [review]
great work, thanks!

**Pull request merged**
