### PR TITLE
Missing operationId for predicates?

### PR DESCRIPTION
**Pull request by RichardBruskiewich**

### CODE REVIEW

**Review by edeutsch — APPROVED** [review]
Seems like a tidy fix. Does not affect the interface at all as far as I'm aware.

**Comment by RichardBruskiewich** [comment]
Just helps in code generation...

**Review by CaseyTa — APPROVED** [review]

**Review by vdancik — CHANGES_REQUESTED** [review]
We should rather remove operationId from /query endpoint

**Comment by RichardBruskiewich** [comment]
OK, decision to remove the `operationsId `from the /query endpoint instead. I'll update the PR accordingly with a commit to this effect.

**Review by edeutsch — APPROVED** [review]

**Review by patrickkwang — APPROVED** [review]

**Review by rtroper — APPROVED** [review]

**Review by CaseyTa — APPROVED** [review]

**Review by bill-baumgartner — APPROVED** [review]

**Review by vdancik — APPROVED** [review]

**Comment by RichardBruskiewich** [comment]
PR reissued as https://github.com/NCATSTranslator/ReasonerAPI/pull/204

**Pull request closed without merging**
