### PR TITLE
Strawman operations{} component

### PR DESCRIPTION
**Pull request by edeutsch**
Add a flexible container that can hold a list of actions, a map of options, and then potentially message URIs or even multiple messages

### CODE REVIEW

**Comment by jzollars** [comment]
@kadelakun

**Comment by dkoslicki** [comment]
@edeutsch @patrickkwang Is this on the TRAPI agenda to get into the "official" TRAPI spec?

**Comment by edeutsch** [comment]
yes, we'll get this into TRAPI 1.2 before release. should be easy.

**Comment by edeutsch** [comment]
This PR is withdrawn in favor of #262

**Pull request closed without merging**
