### PR TITLE
Remove relation from query edge

### PR DESCRIPTION
**Pull request by vdancik**
This addresses inconsistency pointed out in #234

### CODE REVIEW

**Comment by RichardBruskiewich** [comment]
Hi @vdancik and @edeutsch, are we now documenting the "source" relation of an edge somewhere else, in EPC attributes, in such a manner that it is accessible to some user query? 

I'd sort of like @sierra-moxon, @cmungall and @mbrush  to assess this proposal, since as far as I know (and my understanding of the Biolink Model maybe out-of-date at this moment), the `relation` field in the model is meant to record the _original_ predicate (e.g. RO term?) that an external knowledge source uses to characterize the relationship captured by the edge.

Whether or not we remove it from the `QEdge` would depend on whether or not there remains any use case for Translator users searching for edges in knowledge sources which have such an external predicate (e.g. RO term) in the knowledge graph. 

Perhaps not... But all the same, I'd prefer that @sierra-moxon, @cmungall and, perhaps, @mbrush, express their opinions about this before I approve this PR.

**Comment by edeutsch** [comment]
Thanks Richard.

To clarify slightly, this PR only addresses the removal of the `relation` property in the *query edge* QEdge.

The troubles are:
1. predicates is now a list
2. but relation is still a scalar
3. if we switched relation to relations (a list), it's not clear how it should mesh with the predicates list
4. We have not observed anyone using relation since predicates (which must be a biolink model predicate) seems sufficient
For these reasons, we are proposing to remove it.

We actually have a similar problem with relation in the knowledge graph Edge, but that is not addressed in the PR.

**Comment by vdancik** [comment]
I am all for removing relations from knowledge-graph edges and using attributes with `biolink:relation` type to provide that information. Constrained queries can then be used to filter results for a giver relation.

**Review by CaseyTa — APPROVED** [review]

**Comment by cmungall** [comment]
relation is a holdover from previous translator iteration where we needed generic and specific predicates. now we just use predicate

**Review by RichardBruskiewich — APPROVED** [review]
Chris Mungall's comments helped me finalize my decision to approve. You can probably remove the other reviewers (including Chris.. he didn't explicitly do the review but his comment can be taken as an approval).

**Review by sierra-moxon — APPROVED** [review]

**Comment by vdancik** [comment]
I have updated this PR to remove relation from knowledge graph edge to reflect a proposed change in the Biolink model [#761 deprecate relation, add "original_" subject, predicate, object edge properties](https://github.com/biolink/biolink-model/issues/761)

**Pull request merged**
