### PR TITLE
Added LogEntry description to TranslatorReasonerAPI.yaml

### PR DESCRIPTION
**Pull request by webyrd**
Added description of LogEntry.

### CODE REVIEW

**Comment by patrickkwang** [comment]
Very nice. Some of this feels even a bit _too_ thorough, encompassing not just what `LogEntry` is and how to use it, but also rationale for making it that way. I think such rationale is more appropriate as a commit message or PR comment.

**Comment by webyrd** [comment]
> Very nice. Some of this feels even a bit _too_ thorough, encompassing not just what `LogEntry` is and how to use it, but also rationale for making it that way. I think such rationale is more appropriate as a commit message or PR comment.

I could certainly move the rationale to commit message or PR comment. In my experience, these aren't the most discoverable comments.  A rationale document consolidating the intent information might be better, but would require extra work.

**Review by edeutsch — CHANGES_REQUESTED** [review]
ha, I agree it reads as being a bit too honest, exposing your innermost thoughts, rather than typical dry documentation. But fine with me.

Note that there are CI errors that need to be fixed before merging:
Travis is brutal about lines longer than 79 characters:
  201:80    error    line too long (88 > 79 characters)  (line-length)

  202:80    error    line too long (92 > 79 characters)  (line-length)

  203:80    error    line too long (91 > 79 characters)  (line-length)

  204:80    error    line too long (92 > 79 characters)  (line-length)

  205:80    error    line too long (87 > 79 characters)  (line-length)

  206:80    error    line too long (89 > 79 characters)  (line-length)

  207:80    error    line too long (93 > 79 characters)  (line-length)

  208:80    error    line too long (92 > 79 characters)  (line-length)

  209:80    error    line too long (91 > 79 characters)  (line-length)

  210:80    error    line too long (93 > 79 characters)  (line-length)

  211:80    error    line too long (94 > 79 characters)  (line-length)

**Review by bill-baumgartner — APPROVED** [review]

**Comment by webyrd** [comment]
I have edited the LogEntry description, removing context, and shortening lines.  Here is the removed motivation and context:

       The intent of the LogEntry class is to provide a minimum level
        of compatibility for logging information that can be
        communicated between componenents using TRAPI, in order to
        help humans track down cross-component problems, and perhaps
        (at some point) to help software with automatic diagnosis of
        problems across Translator components.  Since it is not yet
        clear which logging information will be most useful, we have
        decide to keep the LogEntry format simple and flexible.

**Review by edeutsch — APPROVED** [review]
Good now, thanks!

**Review by patrickkwang — APPROVED** [review]

**Review by vdancik — APPROVED** [review]

**Review by rtroper — APPROVED** [review]

**Pull request merged**
