### PR TITLE
Make predicate required and cleanup

### PR DESCRIPTION
**Pull request by edeutsch**
Make predicate required and not nullable and clean up examples, definitions, and make the allOf to oneOf switch for validator compatibility

### CODE REVIEW

**Review by edgargaticaCU — APPROVED** [review]

**Review by vdancik — APPROVED** [review]

**Review by RichardBruskiewich — APPROVED** [review]

**Review by ehinderer — APPROVED** [review]

**Review by andrewsu — APPROVED** [review]

**Comment by marcdubybroad** [comment]
Just to verify, does this mean that this query would be invalid (no predicate)?
```
  {
    "message": {
      "query_graph": {
        "edges": {
          "e00": {
            "subject": "n01",
            "object": "n00"
          }
        },
        "nodes": {
          "n00": {
            "categories": ["biolink:Gene"]
          },
          "n01": {
            "ids": ["MONDO:0011936"],
            "categories": ["biolink:DiseaseOrPhenotypicFeature"]
          }
        }
      }
    }
  }
```

**Comment by edeutsch** [comment]
Correct, that would become a schema violation. Is that okay? Or do we want to support such loose queries?
If one simply added a predicate biolink:related_to, that would have the same meaning I suppose, and would be legal under the proposed scheme.

**Comment by marcdubybroad** [comment]
Should we also require categories then on nodes? Just trying to stay consistent on the rules for the json query.

**Comment by edeutsch** [comment]
I think the general sentiment was that if you specify a CURIE, then a category was either redundant or potentially conflicting. Many felt that if you provide a CURIE, you should not provide a category. But there was some disagreement as well.

**Review by MarkDWilliams — APPROVED** [review]

**Comment by vdancik** [comment]
@marcdubybroad actually the PR only specifies that a **knowledge-graph** edge is required; predicate in QEdge remains optional and your query example will still be valid.

**Review by marcdubybroad — APPROVED** [review]

**Review by RichardBruskiewich — APPROVED** [review]

**Pull request merged**
