### PR TITLE
Add explicit HTTP status codes

### PR DESCRIPTION
**Pull request by edeutsch**
Provide a complete set of HTTP status codes and their meanings and contents

### CODE REVIEW

**Comment by CaseyTa** [comment]
If we receive a valid query for which we find no results, should we return an empty KG with status 200 or 404? 

Should there be a distinction in responses between 
1. A Translator component has the resources to operate on a valid query but finds no results
1. A Translator component does not have the resources (e.g., the requested nodes or edge types are not in the component's KG) to operate on the given query?

**Comment by patrickkwang** [comment]
Note the [tests](https://travis-ci.com/github/NCATS-Tangerine/NCATS-ReasonerStdAPI/builds/178486545) are failing because several of the `description`s are too long.
Use multiline strings: https://stackoverflow.com/a/21699210/13242055

**Comment by patrickkwang** [comment]
I think it's a good idea to define all of these codes, but I don't think the Message is the right payload for most of them. 404 500 and can probably just have a `type: string` body, and we should discuss the correct form for the 400 body, to address #132.

**Comment by edeutsch** [comment]
fixed the description lines in the revised PR

**Comment by edeutsch** [comment]
> If we receive a valid query for which we find no results, should we return an empty KG with status 200 or 404?

Although I am not fond of it, I think general best web services practice is to return a 404.
(thus making it difficult to distinguish between a valid query with no good answer and hitting an endpoint with /qeury misspelled)

**Comment by edeutsch** [comment]
> Should there be a distinction in responses between
>
>   1. A Translator component has the resources to operate on a valid query but finds no results
>   2. A Translator component does not have the resources (e.g., the requested nodes or edge types are not in the component's KG) to operate on the given query?

I do not feel it is necessary to have different HTTP codes for such nuances. These would both be 404. The way we report such differences (using the existing `extended` schema constructs) is:
- Message.message_code contains different strings such as 'NoSuitableAssociationsFound' or 'NoSuitableKPsFound'
- Message.code_description contains a human-readable sentence describing the problem
- Message.log contains a trail of logging showing how things were going right until things started to go bad so that a user/tester can understand the problem a bit better.

We could have a common agreed upon set of Message.message_codes documented somewhere.

**Comment by patrickkwang** [comment]
I think "no results" should be a 200. Imagine a sort of "is it true that..." question in which you have two nodes with specified CURIEs connected by an edge with specified predicate. The answer to the implied question may be "no". In that case, no server error has occurred, and the server correctly responds that it can find no evidence for this assertion. 0 results is just an extreme case of N results and should not be treated differently by the server. As @edeutsch points out, 404 is for cases like misspelled URLs where the server actually fails to fulfill the client's request.

Providing feedback about _why_ no results were found is tricky, especially if the server is an ARA. Is there a good reason to treat no-results cases differently than few-results cases? Either way, the client is likely to ask "why didn't I get more?" Rather than worry about delivering concise "error" codes, I'd think about how servers can provide a more detailed description of the steps they took, including things like "KP1 does not accept this predicte", "KP2 did not recognize this CURIE", and "KP3 happily returned 0 results."

**Comment by webyrd** [comment]
I agree with @patrickkwang's last comment.  No results is different than an erroneous query, or a query in which an exceptional condition occurred.

> Rather than worry about delivering concise "error" codes, I'd think about how servers can provide a more detailed description of the steps they took, including things like "KP1 does not accept this predicte", "KP2 did not recognize this CURIE", and "KP3 happily returned 0 results."

I agree.

**Comment by rtroper** [comment]
A 404 on a valid query with no results could create a red herring, leading the user on a fruitless effort to figure out what's wrong with their query. I definitely advocate 200 in this case.

**Pull request merged**
