### PR TITLE
Edit the top-level README with current information

### PR DESCRIPTION
**Pull request by edeutsch**
Refine the top-level README to provide current information

### CODE REVIEW

**Comment by CaseyTa** [comment]
The 2 Google Docs (development agenda and high level summary) are not publicly accessible. 

I don't think we should make the Agenda notes publicly available unless we at least remove the Zoom link with the embedded password. There may be other information in the agenda that we don't want shared publicly. 

I think the summary document should be fine to make public.

**Comment by patrickkwang** [comment]
I think we should avoid having any links to Google Docs. Not only do you run into permissions issues, but documents there just feel too ephemeral. Anything critical we should copy into Markdown documentation in this repo.

**Comment by edeutsch** [comment]
I have updated the pull request to remove links to Google docs and made other cosmetic changes. Please re-review

**Comment by patrickkwang** [comment]
Do we not want a top-level header that says "Translator Reasoner API"? It's basically the title of the homepage of the project.

**Comment by edeutsch** [comment]
okay, you're right. Fixed. That looks better.

**Pull request merged**
