### PR TITLE
Update supporting_publications_specification.md

### PR DESCRIPTION
**Pull request by mbrush**
Adding an important clarification about retrieval source urls vs publications

### CODE REVIEW

**Review by edeutsch — COMMENTED** [review]
Maybe fix spelling of "avaialble"?

Can we provide a compelling most common example to illustrate the "Important Clarification"? Although there's nothing wrong with the statement, I'm not really able to envision an example that helps me truly understand this. Seems a bit abstract.

**Comment by mbrush** [comment]
@edeutsch I fixed the typo and added a clarifying example - hope this helps!

**Review by RichardBruskiewich — CHANGES_REQUESTED** [review]
Generally fine.
I fixed a few small typos in an associated PR (which see)

**Review by edgargaticaCU — APPROVED** [review]

**Review by edeutsch — APPROVED** [review]
looks great now, thanks for the additional info

**Review by uhbrar — APPROVED** [review]

**Pull request merged**
