### PR TITLE
Add templates for metadata that should be there

### PR DESCRIPTION
**Pull request by edeutsch**

### CODE REVIEW

**Comment by vdancik** [comment]
We can add x-trapi: https://github.com/NCATSTranslator/translator_extensions

**Review by vdancik — APPROVED** [review]

**Review by brettasmi — APPROVED** [review]
👍

**Review by patrickkwang — APPROVED** [review]

**Comment by CaseyTa** [comment]
Minor suggestion: the x-translator definition specifically enumerates the values for component and team; could be helpful to include that information. https://github.com/NCATSTranslator/translator_extensions/blob/main/x-translator/smartapi_x-translator_schema.json
Either way, I will approve

**Review by CaseyTa — APPROVED** [review]

**Comment by edeutsch** [comment]
@CaseyTa should we add a link to that json as an external documentation item?

**Review by rtroper — APPROVED** [review]

**Review by CaseyTa — APPROVED** [review]

**Review by bill-baumgartner — APPROVED** [review]

**Review by marcdubybroad — APPROVED** [review]

**Pull request merged**
